spring.application.name=config-server
spring.cloud.config.server.git.username=${CONFIG_GIT_USERNAME}
spring.cloud.config.server.git.password=${CONFIG_GIT_PASSWORD}
spring.cloud.config.server.git.uri=https://github.com/Vishnu-9293/Equipment-Tracking-System-Configuration.git
#config server has pulled application.properties  file from the repo
management.endpoints.web.exposure.include=*
spring.cloud.config.server.git.skipSslValidation=true
spring.cloud.config.server.git.clone-on-start=true
server.port=8088

# Disable DataSource auto-configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration