spring.application.name=PLATFORM-SERVICE
server.port=8086
spring.cloud.config.enabled=false

server.error.include-stacktrace=on-param
server.error.include-message=always

# EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/platform_db?createDatabaseIfNotExist=true&serverTimezone=Asia/Kolkata&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=false

# LOGGING
logging.level.root=INFO
logging.level.com.equiptrack=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# ACTUATOR
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# TRACING
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans