server.port=8084
spring.application.name=api-gateway

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Gateway Routes
spring.cloud.gateway.routes[0].id=equipment-service
spring.cloud.gateway.routes[0].uri=lb://equipment-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/equipment/**,/api/dashboard/**,/api/vendors/**

spring.cloud.gateway.routes[1].id=downtime-trend
spring.cloud.gateway.routes[1].uri=lb://downtime-trend
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/downtime/**,/api/reports/**,/api/analytics/**

spring.cloud.gateway.routes[2].id=MAINTENANCE-SERVICE
spring.cloud.gateway.routes[2].uri=lb://MAINTENANCE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/maintenance-tasks/**
spring.cloud.gateway.routes[3].uri=lb://alerts-performance-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/alerts/**,/api/performance-metrics/**

spring.cloud.gateway.routes[4].id=spare-service
spring.cloud.gateway.routes[4].uri=lb://spare-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/spare-parts/**,/api/spare-parts-requests/**,/api/stock-movements/**

spring.cloud.gateway.routes[5].id=platform-service
spring.cloud.gateway.routes[5].uri=lb://PLATFORM-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/users/**

# Discovery Locator
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Actuator
management.endpoints.web.exposure.include=*