// src/components/VendorForm2.jsx
import React, { useState, useEffect } from "react";
import "bootstrap/dist/css/bootstrap.min.css";

function VendorForm2({
  defaultValues,
  vendors,
  loading,
  addVendor = () => Promise.resolve(),
  onChange,
}) {
  const [formData, setFormData] = useState(defaultValues ?? {});
  const [errors, setErrors] = useState({});
  const [showModal, setShowModal] = useState(false);

  const [newVendorData, setNewVendorData] = useState({
    vendorName: "",
    vendorEmail: "",
    vendorID: "",
  });
  const [modalErrors, setModalErrors] = useState({});

  useEffect(() => {
    setFormData(defaultValues ?? {});
    setErrors({});
  }, [defaultValues]);

  const generateVendorID = () => {
    // This is just for display - actual ID will be generated by backend
    const nums = vendors
      .map((v) => String(v.vendorId ?? ""))
      .map((id) => {
        const m = id.match(/^VND-(\d+)$/);
        return m ? parseInt(m[1], 10) : 0;
      });
    const max = nums.length ? Math.max(...nums) : 1000;
    const next = max + 1;
    return `VND-${next}`;
  };

  const handleVendorSelect = (e) => {
    const val = e.target.value;
    if (val === "__NEW__") {
      setShowModal(true);
      setNewVendorData({
        vendorName: "",
        vendorEmail: "",
        vendorID: generateVendorID(),
      });
      setModalErrors({});
      return;
    }
    const vendor = vendors.find((v) => v.vendorId === val);
    const updated = {
      vendorID: vendor?.vendorId ?? "",
      vendorName: vendor?.vendorName ?? "",
      vendorEmail: vendor?.contactEmail ?? "",
    };
    setFormData(updated);
    setErrors((prev) => ({ ...prev, vendorName: "", vendorEmail: "" }));
    onChange?.(updated);
  };

  const handleModalChange = (e) => {
    const { name, value } = e.target;
    setNewVendorData((prev) => ({ ...prev, [name]: value }));
    if (modalErrors[name]) setModalErrors((prev) => ({ ...prev, [name]: "" }));
  };

  const handleRegisterVendor = async () => {
    const newErrors = {};
    if (!newVendorData.vendorName.trim())
      newErrors.vendorName = "Vendor Name is required";
    if (!newVendorData.vendorEmail.trim())
      newErrors.vendorEmail = "Vendor Email is required";
    if (Object.keys(newErrors).length) {
      setModalErrors(newErrors);
      return;
    }
    try {
      const newVendor = {
        vendorName: newVendorData.vendorName,
        contactEmail: newVendorData.vendorEmail,
      };
      const response = await addVendor(newVendor);
      // Select the newly created vendor in the form
      const updated = {
        vendorID: response.vendorId,
        vendorName: response.vendorName,
        vendorEmail: response.contactEmail,
      };
      setFormData(updated);
      onChange?.(updated);
      setShowModal(false);
    } catch (error) {
      console.error("Failed to register vendor:", error);
      alert("Failed to register vendor. Please try again.");
    }
  };

  const handleBlur = (e) => {
    const { name, value } = e.target;
    let message = "";
    if (name === "vendorName" && !value) message = "Vendor Name is required";
    if (name === "vendorEmail" && !value) message = "Vendor Email is required";
    if (message) setErrors((prev) => ({ ...prev, [name]: message }));
  };

  return (
    <>
      <div className="card">
        <div
          className="card-header text-white"
          style={{ backgroundColor: "var(--primary-dark)" }}
        >
          <h4 className="mb-0">Vendor Details</h4>
        </div>
        <div className="card-body">
          <div className="mb-3">
            <label htmlFor="vendorID" className="form-label">
              Vendor ID
            </label>
            <input
              type="text"
              id="vendorID"
              className="form-control"
              placeholder="Vendor ID is auto-filled"
              value={formData.vendorID ?? ""}
              readOnly
            />
          </div>

          <div className="mb-3">
            <label htmlFor="vendorSelect" className="form-label">
              Vendor <span className="text-danger">*</span>
            </label>
            <select
              id="vendorSelect"
              name="vendorSelect"
              className={`form-select ${errors.vendorName ? "is-invalid" : ""}`}
              value={formData.vendorID ?? ""}
              onChange={handleVendorSelect}
            >
              <option value="">
                {loading ? "Loading..." : "Select Vendor"}
              </option>
              {vendors.map((v) => (
                <option key={v.vendorId} value={v.vendorId}>
                  {v.vendorName}
                </option>
              ))}
              <option value="__NEW__">Not found! Register new Vendor</option>
            </select>
            {errors.vendorName && (
              <div className="invalid-feedback d-block">
                {errors.vendorName}
              </div>
            )}
          </div>

          <div className="mb-3">
            <label htmlFor="vendorEmail" className="form-label">
              Vendor Email <span className="text-danger">*</span>
            </label>
            <input
              type="email"
              id="vendorEmail"
              name="vendorEmail"
              className={`form-control ${
                errors.vendorEmail ? "is-invalid" : ""
              }`}
              placeholder="Vendor Email"
              value={formData.vendorEmail ?? ""}
              readOnly={Boolean(formData.vendorEmail)} // editable only if empty
              onChange={(e) => {
                const updated = { ...formData, vendorEmail: e.target.value };
                setFormData(updated);
                onChange?.(updated);
              }}
              onBlur={handleBlur}
            />
            {errors.vendorEmail && (
              <div className="invalid-feedback d-block">
                {errors.vendorEmail}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Modal for registering new vendor */}
      {showModal && (
        <>
          <div className="modal-backdrop show" />
          <div className="modal show d-block" tabIndex="-1">
            <div className="modal-dialog">
              <div className="modal-content">
                <div className="modal-header">
                  <h5 className="modal-title">Register New Vendor</h5>
                  <button
                    type="button"
                    className="btn-close"
                    onClick={() => setShowModal(false)}
                  />
                </div>
                <div className="modal-body">
                  <div className="mb-3">
                    <label htmlFor="modalVendorID" className="form-label">
                      Vendor ID
                    </label>
                    <input
                      type="text"
                      id="modalVendorID"
                      className="form-control"
                      value={newVendorData.vendorID}
                      readOnly
                    />
                  </div>
                  <div className="mb-3">
                    <label htmlFor="modalVendorName" className="form-label">
                      Vendor Name <span className="text-danger">*</span>
                    </label>
                    <input
                      type="text"
                      id="modalVendorName"
                      name="vendorName"
                      className={`form-control ${
                        modalErrors.vendorName ? "is-invalid" : ""
                      }`}
                      value={newVendorData.vendorName}
                      onChange={handleModalChange}
                      placeholder="Enter vendor name"
                    />
                    {modalErrors.vendorName && (
                      <div className="invalid-feedback d-block">
                        {modalErrors.vendorName}
                      </div>
                    )}
                  </div>
                  <div className="mb-3">
                    <label htmlFor="modalVendorEmail" className="form-label">
                      Vendor Email <span className="text-danger">*</span>
                    </label>
                    <input
                      type="email"
                      id="modalVendorEmail"
                      name="vendorEmail"
                      className={`form-control ${
                        modalErrors.vendorEmail ? "is-invalid" : ""
                      }`}
                      value={newVendorData.vendorEmail}
                      onChange={handleModalChange}
                      placeholder="Enter vendor email"
                    />
                    {modalErrors.vendorEmail && (
                      <div className="invalid-feedback d-block">
                        {modalErrors.vendorEmail}
                      </div>
                    )}
                  </div>
                </div>
                <div className="modal-footer">
                  <button
                    type="button"
                    className="btn btn-secondary"
                    onClick={() => setShowModal(false)}
                  >
                    Cancel
                  </button>
                  <button
                    type="button"
                    className="btn"
                    style={{ backgroundColor: "var(--primary-dark)" }}
                    onClick={handleRegisterVendor}
                  >
                    Register Vendor
                  </button>
                </div>
              </div>
            </div>
          </div>
        </>
      )}
    </>
  );
}

export default VendorForm2;
